### ISSUE TITLE
MPI does not work

### ISSUE THREAD

**Issue by finkandreas** [UoB-HPC/TeaLeaf#2]
I was trying to run the kokkos testcases with MPI, but it does not seem to work. Trying to dig into the source code a bit, I realized that the implementation cannot work.
To me it seems that the main idea of  packing/unpacking of halos is done in `drivers/remote_halo_driver.c`, which passes a buffer pointer to `run_pack_or_unpack(...)`. However in kokkos_orig/kokkos_np this buffer is completely ignored and the exchange is written its own buffer. The data that is sent in drivers//remote_halo_driver.c does not care about this buffer that was written into and transfers the original buffer (as it assumed that `run_pack_or_unpack()` was writing the data there).

The kokkos folder itself does not work at all for me, even without MPI, just single thread, tested with the 512x512 example.

I'm kind of lost, what is supposed to work, and what is not a valid test case. Should all combinations work with MPI, or is it considered obsolete to use MPI and if it's obsolete why?

**Comment by mattmartineau** [comment]
I didn't expect MPI would work properly as it hasn't been used yet but I am surprised to hear that the standard version isn't working! It definitely should be working as it has been used quite extensively for OpenMP and CUDA runs. I will take a look when I get a chance this weekend.

With regards to MPI it is potentially straightforward to hook them up so I will try when I get a chance. If you work it out before then chuck me a pull request.

**Comment by mattmartineau** [comment]
There were some minor issues to work through to get MPI working, it should now be functional for the kokkos and kokkos_orig kernel sets. I tested with some strange task counts and it seemed to work OK. There is something wrong with the kokkos_np set so don't use that, and I haven't tried multi-GPU, but I am fairly sure there will be some issues with bounds on some of the kernels.

I won't get a chance to look again for a while now, but hopefully the updates will help.

If you standardise the problem sets for your research it would be great if you could raise a pull request with the update when you're done.

Thanks
Matt

**Comment by finkandreas** [comment]
Yes I can confirm that kokkos and kokkos_orig are working now. I created a pull request for kokkos_np. The problem was that it did not work with non-square chunks (i.e. even with only one MPI process with x_cells != y_cells did not converge)
