### ISSUE TITLE
Missing kokkos files

### ISSUE THREAD

**Issue by finkandreas** [UoB-HPC/TeaLeaf#4]
Trying to compile the source code I get missing include files (e.g. impl/Kokkos_OldMacros.hpp). Using KOKKOS_PATH=/path/to/local/trilinos/packages/kokkos works just fine.
Did you forget to commit some of the files?

**Comment by mattmartineau** [comment]
I just updated and tried with a fresh copy, seemed to work but let me know if any issues still persist.

**Comment by finkandreas** [comment]
Still the same problem. Are you sure you do not have the variable KOKKOS_PATH exported in your shell?
This is the error I get:

`g++ -O3 -march=native -funroll-loops -std=c++11  -fopenmp -I./ -Ic_kernels/kokkos/kokkos_src/core/src -Ic_kernels/kokkos/kokkos_src/containers/src -Ic_kernels/kokkos/kokkos_src/algorithms/src -Ic_kernels/kokkos  -DENABLE_PROFILING -DOPENMP -c c_kernels/kokkos/set_chunk_state.cpp -o obj/kokkos/set_chunk_state.o`
`In file included from c_kernels/kokkos/kokkos_src/core/src/Kokkos_Core_fwd.hpp:51:0,`
`                 from c_kernels/kokkos/kokkos_src/core/src/Kokkos_Core.hpp:50,`
`                 from c_kernels/kokkos/kokkos_shared.hpp:3,`
`                 from c_kernels/kokkos/set_chunk_state.cpp:1:`
`c_kernels/kokkos/kokkos_src/core/src/Kokkos_Macros.hpp:65:37: fatal error: impl/Kokkos_OldMacros.hpp: No such file or directory`
` #include <impl/Kokkos_OldMacros.hpp>`
`                                     ^`
`compilation terminated.`

**Comment by mattmartineau** [comment]
Did you pull the changes? I did a fresh pull and it worked, I can also see the file <impl/Kokkos_OldMacros.hpp> if I navigate through this github GUI.

**Comment by finkandreas** [comment]
Oh sorry, I didn't realize that you updated the repo. After doing a pull everything works. Thanks
