### ISSUE TITLE
Floating point exception (CUDA kernel)

### ISSUE THREAD

**Issue by lcebaman** [UoB-HPC/TeaLeaf#9]
Compiled as `make CC=gcc CPP=g++ KERNELS=cuda OPTIONS=-DNO_MPI` I get:
```
Opening tea.out as log file.
Performing this solve with the CUDA CG solver
Floating point exception

```

**Comment by tom91136** [comment]
Project structure updated and retested on newer platforms, please reopen if this still occurs.
